title: "Thanox"
baseurl: ""

theme: "just-the-docs"

plugins:
  - jekyll-polyglot

  # jekyll-polyglot
languages: ["en", "zh"]
default_lang: "en"
exclude_from_localization:
  - "assets/images"
parallel_localization: true
sass: # https://github.com/untra/polyglot/issues/107#issuecomment-598274075
  sourcemap: never
