[versions]
accompanist = "0.36.0"
accompanist-appcompat-theme = "0.36.0"
activity-compose = "1.10.1"
adapter-rxjava2 = "2.11.0"
agp = "8.10.0"
javapoet = "1.13.0"
ksp = "2.0.21-1.0.26"
biometric = "1.4.0-alpha04"
adaptive = "1.2.0-alpha07"
androidx-work = "2.10.1"
coil-compose = "2.7.0"
colormath = "3.6.1"
commons-codec = "1.18.0"
commons-io = "2.19.0"
compose-theme-adapter3 = "1.1.1"
constraint-layout = "2.0.4"
easy-rules-support = "4.1.0"
easy-rules-mvel = "4.1.0"
easy-rules-core = "4.1.0"
#noinspection GradleDependency
guava-android = "33.0.0-android"
interpolator = "1.0.0"
lombok = "1.18.38"
paging-runtime = "3.3.6"
licensesdialog = "2.2.0"
lifecycle-extensions = "2.2.0"
listenablefuture = "9999.0-empty-to-avoid-conflict-with-guava"
mpandroidchart = "v3.1.0"
preference = "1.2.1"
recyclerview = "1.4.0"
relinker = "1.4.5"
rxjava = "2.2.21"
storage = "2.1.0"
timber = "5.0.1"
xcrash-android-lib = "3.1.0"
tinypinyin = "3.0.0"
kotest-assertions = "5.9.1"
libsu = "6.0.0"
mmkv = "1.3.7" # LTS.
orbit = "9.0.0"
androidx-test-runner = "1.6.2"
uiautomator = "2.3.0"
espresso-core = "3.6.1"
androidx-junit = "1.2.1"
appcompat = "1.7.0"
browser = "1.8.0"
codeview = "1.3.9"
compose-bom = "2025.05.01"
compose-material = "1.8.2"
compose-icon-ext = "1.7.8"
compose-material3 = "1.4.0-alpha15"
compose-ui = "1.8.2"
compose-markdown = "0.5.4"
converter-gson = "2.11.0"
junit = "4.13.2"
libchecker-rules-bundle = "40.2"
lottie = "6.6.6"
core-ktx = "1.16.0"
core-splashscreen = "1.0.1"
datastore-preferences = "1.1.3"
kotlin = "2.1.20"
kotlinx-coroutines = "1.10.1"
kotlin-reflect = "2.1.20"
kotlinx-serialization-json-jvm = "1.8.1"
chucker = "4.1.0"
lifecycle-runtime-ktx = "2.9.0"
material = "1.14.0-alpha01"
mockk = "1.14.2"
navigation-compose = "2.9.0"
glide = "4.16.0"
okhttp = "4.12.0"
dagger = "2.56.2"
protobuf-java = "3.25.5"
retrofit = "2.11.0"
room = "2.7.1"
room-compiler = "2.7.1"
swiperefreshlayout = "1.1.0"
stringfog-xor = "5.0.0"
stringfog-plugin = "5.2.0"

[plugins]
agp-lib = { id = "com.android.library", version.ref = "agp" }
agp-app = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
protobuf-gradle-plugin = { id = "com.google.protobuf", version = "0.9.5" }
# https://github.com/gmazzo/gradle-buildconfig-plugin
gmazzo-buildconfig = { id = "com.github.gmazzo.buildconfig", version = "5.5.0" }
gladed-androidgitversion = { id = "com.gladed.androidgitversion", version = "0.4.14" }

[libraries]
accompanist-appcompat-theme = { module = "com.google.accompanist:accompanist-themeadapter-appcompat", version.ref = "accompanist-appcompat-theme" }
accompanist-placeholder-material = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }

androidx-adaptive = { module = "androidx.compose.material3.adaptive:adaptive-android", version.ref = "adaptive" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "androidx-work" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
androidx-interpolator = { module = "androidx.interpolator:interpolator", version.ref = "interpolator" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging-runtime" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-extensions" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "lifecycle-runtime-ktx" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "preference" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-compiler" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
colormath = { module = "com.github.ajalt.colormath:colormath", version.ref = "colormath" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
constraint-layout = { module = "com.android.support.constraint:constraint-layout", version.ref = "constraint-layout" }
easy-rules-support = { module = "org.jeasy:easy-rules-support", version.ref = "easy-rules-support" }
easy-rules-mvel = { module = "org.jeasy:easy-rules-mvel", version.ref = "easy-rules-mvel" }
easy-rules-core = { module = "org.jeasy:easy-rules-core", version.ref = "easy-rules-core" }
guava-android = { module = "com.google.guava:guava", version.ref = "guava-android" }
javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }
licensesdialog = { module = "de.psdev.licensesdialog:licensesdialog", version.ref = "licensesdialog" }
listenablefuture = { module = "com.google.guava:listenablefuture", version.ref = "listenablefuture" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
relinker = { module = "com.getkeepsafe.relinker:relinker", version.ref = "relinker" }
rxjava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava" }
storage = { module = "com.anggrayudi:storage", version.ref = "storage" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
xcrash-android-lib = { module = "com.iqiyi.xcrash:xcrash-android-lib", version.ref = "xcrash-android-lib" }
tinypinyin = { module = "com.github.promeg:tinypinyin", version.ref = "tinypinyin" }
libsu-core = { module = "com.github.topjohnwu.libsu:core", version.ref = "libsu" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest-assertions" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest-assertions" }
mmkv = { module = "com.tencent:mmkv", version.ref = "mmkv" }
orbit-compose = { module = "org.orbit-mvi:orbit-compose", version.ref = "orbit" }
orbit-viewmodel = { module = "org.orbit-mvi:orbit-viewmodel", version.ref = "orbit" }
uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
browser = { module = "androidx.browser:browser", version.ref = "browser" }
# https://github.com/AmrDeveloper/CodeView
codeview = { module = "io.github.amrdeveloper:codeview", version.ref = "codeview" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-material" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "compose-icon-ext" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose-icon-ext" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-ui" }
compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose-ui" }
compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "compose-ui" }
compose-markdown = { module = "com.github.jeziellago:compose-markdown", version.ref = "compose-markdown" }

datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
glide-landscapist = { module = "com.github.skydoves:landscapist-glide", version = "2.4.7" }

junit = { module = "junit:junit", version.ref = "junit" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin-reflect" }
kotlinx-serialization-json-jvm = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-jvm", version.ref = "kotlinx-serialization-json-jvm" }

libchecker-rules-bundle = { module = "com.github.LibChecker:LibChecker-Rules-Bundle", version.ref = "libchecker-rules-bundle" }
chucker-no-op = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }
chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
material = { module = "com.google.android.material:material", version.ref = "material" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

gson = { module = "com.google.code.gson:gson", version = "2.13.1" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version = "6.1" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
dagger-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.2.0" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf-java" }
protobuf-java-util = { module = "com.google.protobuf:protobuf-java-util", version.ref = "protobuf-java" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converter-gson" }
retrofit-adapter-rxjava2 = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "adapter-rxjava2" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }

stringfog-xor = { module = "com.github.megatronking.stringfog:xor", version.ref = "stringfog-xor" }
stringfog-plugin = { module = "com.github.megatronking.stringfog:gradle-plugin", version.ref = "stringfog-plugin" }