name: App

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Dump env
        run: echo ${GITHUB_WORKSPACE}

      - name: Decrypt android key store
        run:  openssl enc -aes-256-cbc -d -K ${{ secrets.K }} -iv ${{ secrets.IV }} -in ${GITHUB_WORKSPACE}/environment/keys/android-key-enc -out ${GITHUB_WORKSPACE}/environment/keys/android.jks

      - name: build
        uses: xdtianyu/actions-android-ci@master
        with:
          args: '"
        source .travis/env.sh;
        source /opt/setup-android-sdk.sh;
        export KEYSTORE_PASS=${{ secrets.KEYSTORE_PASS }};
        export TOKEN=${{ secrets.GH_ACCESS_TOKEN }};
        export USERNAME=${{ secrets.GH_USER_NAME }};
        export ALIAS_NAME=${{ secrets.ALIAS_NAME }};
        export ALIAS_PASS=${{ secrets.ALIAS_PASS }};
        cd android;
        ./scripts/build_prc_release.sh
        "'
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: thanox.apk
          path: out/app/outputs/apk/prc/release/thanox_*.apk

